name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2  # Updated to a specific version known to work

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("tidyverse", "ggplot2", "testthat", "rmarkdown"), dependencies = TRUE)'

    - name: Run tests
      run: |
        Rscript tests/test_analysis.R

    - name: Render R Markdown
      run: |
        Rscript -e 'rmarkdown::render("R/analysis.Rmd")'
