name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.0.0'

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("tidyverse")'
        Rscript -e 'install.packages("ggplot2")'
        Rscript -e 'install.packages("testthat")'
        Rscript -e 'install.packages("rmarkdown")'

    - name: Run tests
      run: |
        Rscript tests/test_analysis.R

    - name: Render R Markdown
      run: |
        Rscript -e 'rmarkdown::render("R/analysis.Rmd")'
