name: R

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.0.0', '4.1.1']  # Updated versions

    steps:
    - uses: actions/checkout@v4

    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v3
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("remotes", "rcmdcheck"))'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Check
      run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
